chrome:
  image: conf_chrome
  links:
   - conf_burp:burp_test
  volumes:
   - /tmp/.X11-unix:/tmp/.X11-unix
  environment:
    DISPLAY: $DISPLAY
    HTTP_PROXY: http://burp_test:8080
conf_burp:
  image: conf_burp
  expose: 
   - "8080"
  volumes:
    - /tmp/.X11-unix:/tmp/.X11-unix
  environment:
    DISPLAY: $DISPLAY

